---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: trailing-whitespace
  - repo: https://github.com/userhas404/pre-commit
    rev: v0.0.1
    hooks:
      - id: spellcheck