---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: trailing-whitespace
  - repo: https://github.com/userhas404d/git-hooks
    rev: 59684290243f85f2d052181ceb46e8b6969f180b
    hooks:
      - id: spellcheck
      files: *